# Generated by Django 3.2.8 on 2023-02-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSharing', '0002_auto_20230207_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='title',
        ),
    ]
