# Generated by Django 3.2.8 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSharing', '0003_remove_filemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
